baseURL = 'https://profenomada.github.io/'
languageCode = 'en-us'
title = 'Blog de un ProfeNomada'

metaDataFormat = "yaml"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Hola! soy Diego, un profe nomada"
      introSubtitle = "ser nomada y estar perdido no son lo mismo"
      introPhoto = "guitarra_portada.jpg"
      #logo = "guitar_logo.png" # --> Aquí va el logo, tengo que poner una imagen
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    # [[languages.en.menu.main]]   Esto lo sacó la mina del video
    #     name = "Top Post"
    #     url = "/en/blog/emoji-support/"
    #     weight = 4

  

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true

  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 - ProfeNomada · All rights reserved"
  favicon = "/favicon.svg"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-blue-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false

  # To hide "Other languages" option if the post is available in multiple languages
  # Can be used at site level or page level
  hideOtherLanguages = false

[params.homepage.social]
  # Global params common for both languages
  title = "Seguime en mis redes"
  description = "Convertite en el músico que quieres ser, ser nomada y estar perdido no son lo mismo."
  twitter = "https://twitter.com/"
  youtube = "https://www.youtube.com/"
  instagram = "https://www.facebook.com/"
  #linkedin = "https://linkedin.com/in/"
  #xing = "https://www.xing.com/profile/"
  #github = "https://github.com/"
  #medium = "https://medium.com/"
  #reddit = "https://reddit.com/"
  #dribbble = "https://dribbble.com/"
  #stackoverflow = "https://stackoverflow.com/"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
